### ISSUE TITLE
Veld omschrijving toevoegen

### ISSUE THREAD

**Issue by jarichypma** [VNG-Realisatie/gemma-notificatiecomponent#16]
Het lijkt me handig om bij een notificatie een veld omschrijving beschikbaar te hebben. Dit veld dient als _human-readable description_. Dit veld kan gebruikt worden in een mailnotificatie of in de applicatie om een gebruiker in eenvoudige en begrijpelijke taal uit te leggen waar de notificatie over gaat.

Ik heb zitten denken of je hiervoor het vel `actie` kunt gebruiken, maar dat lijkt me niet wenselijk aangezien dit veld een andere functie heeft.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Voor notificatie is dit een andere repo. Ik heb je toegevoegd want wellicht moet jij prio aangeven

**Comment by Hugo-ter-Doest** [comment]
Notificaties zijn niet bedoeld om direct aan de eindgebruiker te tonen en notificaties zijn bewust informatie-arm gehouden. De geabonneerde applicaties kan, indien gewenst, de resource ophalen om te beoordelen of de notificatie moet worden getoond en om aanvullende gegevens te verkrijgen die kunnen worden getoond aan de eindgebruiker.
