### ISSUE TITLE
aanmaakDatum hernoemen naar (iets als) datumTijdstipGebeurtenis

### ISSUE THREAD

**Issue by jarichypma** [VNG-Realisatie/gemma-notificatiecomponent#17]
Voorstel: aanmaakDatum hernoemen naar (iets als) datumTijdstipGebeurtenis.

Een veldnaam als datumTijdstipGebeurtenis is beschrijvender dan aanmaakDatum. Dit omdat aanmaakdatum in combinatie met een create-gebeurtenis suggereert dat je bij een mutatie of verwijdering een datumVerwijdering of datumMutatie kunt verwachten. 

Daarnaast suggereert datum (niet zijnde datumTijdstip) dat je geen tijdstip hoeft te verwachten terwijl dit wel relevant is om de volgordelijkheid van de notificaties te bepalen.

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest Voor notificatie is dit een andere repo. Ik heb je toegevoegd want wellicht moet jij prio aangeven

**Comment by sergei-maertens** [comment]
`tijdstip` lijkt me een goeie ook, leunt dichter aan bij het Engelse `timestamp` en dekt alle events zonder te verbose te worden.

**Comment by joeribekker** [comment]
Verplaatst naar project bord: https://github.com/VNG-Realisatie/gemma-zaken/issues/1399
